spring:
   cloud:
      discovery:
         enabled: true
         
eureka:
   client:
      enabled: true
      serviceUrl:
         defaultZone: ${jor.httpScheme:http}://${MS_EUREKA_HOST:localhost}:${MS_EUREKA_PORT:8761}/eureka      
      healthcheck:
         enabled: true       # ensures the application propogates the actuator /health to eureka. Only seems to work properly for UP/DOWN, not OUT_OF_SERVICE 
                             # This is done by registering a HealthCheckHandler bean (EurekaHealthCheckHandler) - if this property is true.
                             # EurekaHealthCheckHandler aggregates status from any HealthIndicators found in context and reports to eureka (UP/DOWN only)

management:   
   endpoints:
      web:
         exposure:
            include: "*"
         
ie:
   jor:
      example:
         configuration:
            from: configServer-remote-repo                             