# set service discovery enabled
spring:
   cloud:
      discovery:
         enabled: true

# register the service on eureka
eureka:
   client:
      enabled: true
      serviceUrl:
         defaultZone: ${http.scheme:http}://${MS_EUREKA_HOST:localhost}:${MS_EUREKA_PORT:8761}/eureka      

# enable all actuator http endpoints
management:   
   endpoints:
      web:
         exposure:
            include: "*"
            
---
spring:
   profiles: ssl

http:
   scheme: https

eureka:
   instance:
      nonSecurePortEnabled: false
      securePortEndabled: true
      securePort: ${server.port}
         
server:
   ssl:
      enabled: true
      keystore: ${MS_KEYSTORE_PATH:classpath:keystore.jks}
      keystorePassword: ${MS_KEYSTORE_PASSWORD:password}
      keyAlias: ${MS_KEYSTORE_ALIAS:localhost}
            