# set eureka defaultZone
eureka:
   client:
      serviceUrl:
         defaultZone: ${http.scheme:http}://${MS_EUREKA_HOST:localhost}:${MS_EUREKA_PORT:8761}/eureka      
   instance:
      hostname: ${MS_HOST:localhost}

# enable all actuator http endpoints
management:   
   endpoint:
      logfile:
         external-file: ./logs/${spring.application.name:service}.log
   endpoints:
      web:
         exposure:
            include: "*"

logging:
   file:
      name: ./logs/${spring.application.name:service}.log

---
spring:
   profiles: ssl

http:
   scheme: https

eureka:
   instance:
      nonSecurePortEnabled: false
      securePortEndabled: true
      securePort: ${server.port}
         
server:
   ssl:
      enabled: true
      keystore: ${MS_KEYSTORE_PATH:classpath:keystore.jks}
      keystorePassword: ${MS_KEYSTORE_PASSWORD:password}
      keyAlias: ${MS_KEYSTORE_ALIAS:localhost}
            